spring.application.name=gateway-service
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1

# Route id
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/public/auth/**
spring.cloud.gateway.routes[1].id=user-service-protected
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**

# Category Route id
spring.cloud.gateway.routes[2].id=category-service
spring.cloud.gateway.routes[2].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/categories/**

eureka.instance.prefer-ip-address=true
jwt.secret=ThisIsA_VeryLongSecretKey_ForJwtMoneyAi_ChangeMe123456
