server:
    port: 8080

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                # 1. API Đăng nhập / Đăng ký (Public)
                - id: user-service
                  uri: lb://USER-SERVICE
                  predicates:
                      - Path=/public/auth/**

                # 2. API Cần xác thực của User
                - id: user-service-protected
                  uri: lb://USER-SERVICE
                  predicates:
                      - Path=/auth/**, /categories/**, /transactions/**

                # 3. Route lấy dữ liệu JSON Swagger của User Service
                - id: openapi-user-service
                  uri: lb://USER-SERVICE
                  predicates:
                      - Path=/v3/api-docs/user-service
                  filters:
                      - RewritePath=/v3/api-docs/user-service, /v3/api-docs
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        hostname: localhost
        ip-address: 127.0.0.1
        prefer-ip-address: true

jwt:
    secret: ThisIsA_VeryLongSecretKey_ForJwtMoneyAi_ChangeMe123456

springdoc:
    swagger-ui:
        urls:
            - name: User Service API
              url: /v3/api-docs/user-service
